echo "<html>"
echo "<head>"
echo "<title>Hello World</title>"
echo "<style>"
echo "  body {"
echo "    font-family: Arial, sans-serif;"
echo "    background-color: #f0f0f0;"
echo "    margin: 0;"
echo "    padding: 0;"
echo "    text-align: center;"
echo "  }"
echo "  h1 {"
echo "    color: #333333;"
echo "    margin-top: 100px;"
echo "  }"
echo "</style>"
echo "</head>"
echo "<body>"
echo "<h1>Hello, World!</h1>"
echo "</body>"
echo "</html>"